### PR TITLE
SlicerDMRI TR read and write results

### PR DESCRIPTION
**Pull request by zhangfanmark**
Need access to upload figures.

### CODE REVIEW

**Comment by fedorov** [comment]
Will add you to the Dropbox folder later tonight!

**Comment by fedorov** [comment]
@zhangfanmark sorry for the delay! I checked now, and I see you are already added to the folder, so hope you are all set. Let me know if anything else is needed!

**Comment by zhangfanmark** [comment]
@fedorov Thanks!  In fact I meant the result figures need to be added into the git repo. I tried to upload a figure while I was doing the pull request but it says one needs a push access to do that. I guess I don't have that.

**Comment by fedorov** [comment]
Ah, I see. I guess you only use the web interface and no repo fork. I will add you.

**Comment by zhangfanmark** [comment]
Thank you!

**Pull request merged**
