### PR TITLE
Update documentation for FreeSurfer

### PR DESCRIPTION
**Pull request by ltirrell**
This updates the seg portion of the docs from last year to use the new `fs2dicom` tool, and also adds a new section for the FreeSurfer SR. 

Of note, I included image showing the results in 3d Slicer (from [here](https://groups.google.com/forum/#!topic/dicom4qi/BD9i2lUklvU) within the structured reporting section. Also, I added some relative links which I'm not sure will work. I could check after this is merged to confirm they are correct.

Lastly, the link for data included here that @pwighton provided is ephemeral. Is there a better place for us to upload it?

### CODE REVIEW

**Comment by fedorov** [comment]
> Lastly, the link for data included here that @pwighton provided is ephemeral. Is there a better place for us to upload it?

Lee, I did add that dataset to the list, see item 6 here: https://dicom4qi.readthedocs.io/en/latest/instructions/seg/

I also sent an email to the dicom4qi google group, see https://groups.google.com/forum/#!topic/dicom4qi/6S01EpiacY8, are you getting those?

**Comment by ltirrell** [comment]
oh yes, i missed that. Is it possible to also include the tarball linked above? This contains a pre-processed FreeSurfer subject, so the end user could just run the `fs2dicom` processing as well

**Comment by fedorov** [comment]
Sure, we can add that too. I will look tomorrow. On the plane approaching Chicago (finally after nearly 12 hours flight delay!).

**Comment by ltirrell** [comment]
no rush! Let me know when it is uploaded, and I could create another PR with the updated link, as well as some formatting changes.

**Comment by fedorov** [comment]
@ltirrell I added the tarball, it is now under SR-TID1500\Dataset5\StructuredReports\fs2dicom. Let me know if anything else is needed!

**Comment by fedorov** [comment]
By the way, just to bring to your attention - please check the title for the section in the table of contents in case this needs to be revised: https://github.com/QIICR/DICOM4QI/blob/master/mkdocs.yml#L40

**Pull request merged**
