### PR TITLE
Update tr.md

### PR DESCRIPTION
**Pull request by ljod**
Update for 2018 by including load/save/vis of FA along tracts.

### CODE REVIEW

**Comment by fedorov** [comment]
@ljod for the new datasets, I suggest you add new ones, and not replace the ones used before. Perhaps this is what you planned to do anyway, but I just wanted to mention it.

**Comment by ljod** [comment]
Thanks! We plan to use the same DWI as before, since the goal is to generate tracts from the DWI.

**Comment by fedorov** [comment]
Makes sense. But do you plan to keep the datasets that do not have FA along tracts? I would think it might be a good idea to have both old (no FA) and new (with FA along the tracts).

**Comment by fedorov** [comment]
> But do you plan to keep the datasets that do not have FA along tracts?

I mean, tractography datasets

**Pull request merged**
